import { c as createAstro, d as createComponent, r as renderTemplate, h as renderComponent, m as maybeRenderHead, g as addAttribute } from '../astro_7b0539fb.mjs';
import { $ as $$Layout } from './100-questions_7f9eb0b1.mjs';
import 'clsx';
import 'html-escaper';
/* empty css                           */
const $$Astro = createAstro();
const $$Blog = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Blog;
  const allPosts = await Astro2.glob(/* #__PURE__ */ Object.assign({"./posts/100-questions.md": () => import('./100-questions_7f9eb0b1.mjs').then(n => n._),"./posts/aesthetics.md": () => import('./aesthetics_6e010d4f.mjs'),"./posts/bidding.md": () => import('./bidding_25bbfaf4.mjs'),"./posts/conviction.md": () => import('./conviction_9323cb6c.mjs'),"./posts/criticallyunderstanding.md": () => import('./criticallyunderstanding_82469001.mjs'),"./posts/digitalnetworking.md": () => import('./digitalnetworking_b7bcdfe3.mjs'),"./posts/environmentaldeterminism.md": () => import('./environmentaldeterminism_c677e26d.mjs'),"./posts/frenchdiscomfort.md": () => import('./frenchdiscomfort_f412dd01.mjs'),"./posts/immunityisafallacy.md": () => import('./immunityisafallacy_77439d1b.mjs'),"./posts/indefence.md": () => import('./indefence_c3d29209.mjs'),"./posts/inertia.md": () => import('./inertia_f5c0cc87.mjs'),"./posts/iwantafrenchsalon.md": () => import('./iwantafrenchsalon_4cba15e9.mjs'),"./posts/latin.md": () => import('./latin_b8bd6b6f.mjs'),"./posts/learned.md": () => import('./learned_fe0f0227.mjs'),"./posts/myhomoeconomics.md": () => import('./myhomoeconomics_0ebfc6ff.mjs'),"./posts/nigeria.md": () => import('./nigeria_57114cf3.mjs'),"./posts/onlegibility.md": () => import('./onlegibility_db99ff7c.mjs'),"./posts/philosophybanter.md": () => import('./philosophybanter_09e53a0a.mjs'),"./posts/poetrydefence.md": () => import('./poetrydefence_a3b6b8e5.mjs'),"./posts/rabbit-duck.md": () => import('./rabbit-duck_6c50c1c6.mjs'),"./posts/rustlings.md": () => import('./rustlings_abf7e639.mjs'),"./posts/stubborn.md": () => import('./stubborn_d3bff5ad.mjs'),"./posts/stupidwriting.md": () => import('./stupidwriting_713540d8.mjs'),"./posts/summer.md": () => import('./summer_3f0e6cab.mjs'),"./posts/understandinghumility.md": () => import('./understandinghumility_d6d1e3ec.mjs')}), () => "../pages/posts/*.md");
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Mindstream." }, { "default": ($$result2) => renderTemplate`${maybeRenderHead()}<div class="blogindex"><p>* = personal thumbs up</p><h4>Main?</h4>${allPosts.map((post) => renderTemplate`<li><a${addAttribute(post.url, "href")}>${post.frontmatter.title}</a></li>`)}<ul><li><a href="/posts/summer">Last week of summer reflections</a></li><li><a href="/posts/iwantafrenchsalon">I Want A French Salon</a></li><li><a href="/posts/aesthetics">A Sense of Aesthetics *</a></li><li><a href="/posts/latin">Latin America Flew Just Under my Radar</a></li><li><a href="/posts/myhomoeconomics">Econ Notepad</a></li><li><a href="/posts/rabbit-duck">Rabbit-Duck</a></li><li><a href="https://hackmd.io/@ecx2VlHIRJSuD55CidtDSw/ByZRgBtOh" target="_blank">Ramblings on the Creative Technologists</a></li><li><a href="/posts/bidding">Edgy Bidding</a></li><li><a href="/posts/stubborn">Stubborn Attachments</a></li><li><a href="/posts/stupidwriting">Stupid Writing *</a></li><li><a href="/posts/poetrydefence">In Defence of Poetry *</a></li><li><a href="/posts/100-questions">100 Questions *</a></li></ul><h4>Dusty</h4><ul><li><a href="https://docs.google.com/document/d/12s-BM5qCFAsGGbUFtHEmtKkc-uUK5CS8cKyg-BA5kS0/edit?usp=sharing" target="_blank">Psychonauts, Biohackers and Distributed Scientific Progress</a></li><li><a href="https://onedropofcoffee.substack.com/p/when-humans-can-no-longer-excel-let" target="_blank">When Humans Can No Longer Excel, Let the Beautiful Prevail.</a></li><li><a href="/posts/environmentaldeterminism">Environmental Determinism is Incomplete</a></li><li><a href="/posts/nigeria">Supporting Talent in Nigeria: Mini-Report</a></li><!-- <li><a href="/posts/rustlings">Rustlings...Ending Chapters</a></li> --><!-- <li><a href="/posts/onlegibility">On Legibility</a></li> --><li><a href="/posts/philosophybanter">Philosophy Banter</a></li></ul><h4>More Personal</h4><ul><li><a href="https://onedropofcoffee.substack.com/p/give-and-take" target="_blank">Give and Take</a></li><li><a href="https://hackmd.io/@ecx2VlHIRJSuD55CidtDSw/SJFZt4n8n" target="_blank">So high school is over?</a></li><li><a href="/posts/inertia">Inertia</a></li><!-- <li><a href="/posts/criticallyunderstanding">Critically Understanding School</a></li>
            <li><a href="/posts/understandinghumility">Understanding Humility as a Virtue</a></li>
            <li><a href="/posts/immunityisafallacy">Immunity is a Fallacy: Groupthink and Cults</a></li>
            <li><a href="/posts/conviction">Conviction</a></li>
            <li><a href="/posts/digitalnetworking">Digital Networking for Dummies</a></li>
            <li><a href="/posts/indefence">A (Not-So) Interesting Public Health Take (Weakly-held)</a></li> --></ul></div>` })}`;
}, "/Users/hamidahoderinwale/regular-ring/src/pages/blog.astro", void 0);

const $$file = "/Users/hamidahoderinwale/regular-ring/src/pages/blog.astro";
const $$url = "/blog";

export { $$Blog as default, $$file as file, $$url as url };
